# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_colour',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
