# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161111_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
