# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20161118_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='project',
            new_name='projects',
        ),
    ]
