# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('startup', 'Startup'), ('small', 'Small Business')], max_length=10),
        ),
    ]
