# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.Client'),
        ),
    ]
